# Generated by Django 3.1.3 on 2020-11-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='data_nascimento',
            new_name='data_matricula',
        ),
    ]
